version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.nvidia
    ports:
      - "8000:8000"
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - LOG_LEVEL=INFO
      - LOG_FORMAT=json
      - AUTH_REQUIRED=true
      - PROMETHEUS_ENABLED=true
      - ENABLE_GPU_ACCELERATION=true
      - ENABLE_TENSORRT=true
      - ENABLE_GPTQ=true
      - ENABLE_AWQ=true
      - QUANTIZATION_BIT_WIDTH=4
      - ENABLE_FP8=true
      - ENABLE_FLASH_ATTENTION_2=true
      - QUANTIZATION_CACHE_DIR=/tmp/quantization_cache
      - CUDA_VISIBLE_DEVICES=0
    volumes:
      - ./data:/app/data
      - /tmp/quantization_cache:/tmp/quantization_cache
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - api

  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    ports:
      - "3000:3000"
    depends_on:
      - prometheus