global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'hana-ai-api'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['api:9090']
    scheme: http

  - job_name: 'node'
    static_configs:
      - targets: ['api:9100']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'nvidia-gpu'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['api:9400']
    scrape_interval: 5s  # More frequent scraping for GPU metrics
    scheme: http
    
  - job_name: 'nvidia-dcgm'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['dcgm-exporter:9400']
    scrape_interval: 5s
    scheme: http
    
  - job_name: 't4-tensorrt-metrics'
    metrics_path: '/metrics/tensorrt'
    static_configs:
      - targets: ['api:9090']
    scheme: http
    
  - job_name: 't4-gpu-telemetry'
    metrics_path: '/metrics/gpu_telemetry'
    static_configs:
      - targets: ['api:9090']
    scrape_interval: 5s
    scheme: http

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

rule_files:
  - "t4_gpu_alert_rules.yml"